title: Donal Tuohy
description: > # this means to ignore newlines until "baseurl:"
  A small site where I plan to share some of my thoughts.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://donaltuohy.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Freeman # add your name
author-img: profle.png # add your photo
about-author: I am a software engineer on back end development. Always hungry to keep learning. # add description
social-github: donaltuohy # add your Github handle
social-linkedin: donaltuohy
social-email: donaltuohy@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
